In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr5=np.identity(3)
arr5


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
import numpy as np
arr6 = np.array([[1,2,3,4],[5,6,7,8]])
arr6

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr6.shape

(2, 4)

In [12]:
arr8=np.arange(24)
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [16]:
arr8=np.arange(24).reshape(6,4)
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
arr8.diagonal
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
l1=[1,2,3,4,5]
print(l1[1:3])

[2, 3]


In [31]:
arr8[2:4]


array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
arr8[:,:3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18],
       [20, 21, 22]])

In [36]:
arr8[2:4,:3]

array([[ 8,  9, 10],
       [12, 13, 14]])

In [38]:
arr7=np.array([1,2,3,4,5,6])
arr6=np.array([4,5,6,7,8,9])
arr7-arr6
arr7*arr6

array([ 4, 10, 18, 28, 40, 54])

In [39]:
arrz=np.arange(6).reshape(2,3)
arrx=np.arange(6,12).reshape(3,2)
arrz.dot(arrx)

array([[ 28,  31],
       [100, 112]])

In [42]:
arr8*2


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [45]:
for i in np.nditer(arr8):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [46]:
arr8.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [47]:
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [48]:
arr8>10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [51]:
arr8[arr8>10]

ValueError: cannot reshape array of size 13 into shape (4,6)